import type { CueSheet } from '@maxmellon/cue-parser';

/**
 * セトリ画像の組版と描画。
 *
 * React には依存しない。計測(planSetlistLayout)と描画(renderSetlistPage)を分けてあるので、
 * 縮尺を探るために何度レイアウトし直しても画面はちらつかない。
 *
 * 出力サイズは SETLIST_SIZES から選ぶ。寸法はすべて 1080 幅を基準にした比で持っているので、
 * 幅が変われば余白も級数も同じ比で付いてくる。高さの違いは 1 枚に入る曲数だけに効く。
 */

export type SetlistSizeId = 'story' | 'portrait';

export interface SetlistSize {
  id: SetlistSizeId;
  width: number;
  height: number;
  /** 用途。プレビューの下に出す */
  note: string;
  /**
   * 詰めて組むときの縮尺の下限。ここまで小さくしても入らなければページを割る。
   * 3:4 は 1 枚で投げる絵なので、縦の短さぶんは文字を落として 1 枚に収める
   */
  minScale: number;
}

export const SETLIST_SIZES: readonly SetlistSize[] = [
  {
    id: 'story',
    width: 1080,
    height: 1920,
    note: 'Instagram / TikTok ストーリー向け',
    minScale: 0.62,
  },
  {
    id: 'portrait',
    width: 1280,
    height: 1707,
    note: 'X などのタイムライン向け(3:4)',
    minScale: 0.3,
  },
];

export const DEFAULT_SETLIST_SIZE: SetlistSize = SETLIST_SIZES[0];

/* app/globals.css のトークンの写し。あちらを触ったらこちらも揃える。
   色相は使わない。区別は明度・字間・罫線だけで付ける。 */
const COLOR_BG = '#000000';

interface Palette {
  fg: string;
  muted: string;
  rule: string;
  ruleStrong: string;
  hairline: string;
  shadow: string;
  /** 前景の下に敷く覆いの色 */
  scrim: string;
}

/** 既定。黒地に白文字 */
const LIGHT_PALETTE: Palette = {
  fg: '#f2f2f3',
  muted: '#a1a1a8',
  rule: 'rgba(255, 255, 255, 0.16)',
  ruleStrong: 'rgba(255, 255, 255, 0.45)',
  hairline: 'rgba(255, 255, 255, 0.10)',
  shadow: 'rgba(0, 0, 0, 0.72)',
  scrim: '0, 0, 0',
};

/** 明るい写真の上に黒文字を載せるとき */
const DARK_PALETTE: Palette = {
  fg: '#0b0b0c',
  muted: '#3b3b42',
  rule: 'rgba(0, 0, 0, 0.22)',
  ruleStrong: 'rgba(0, 0, 0, 0.55)',
  hairline: 'rgba(0, 0, 0, 0.14)',
  shadow: 'rgba(255, 255, 255, 0.72)',
  scrim: '255, 255, 255',
};

export interface SetlistTheme {
  textColor: 'light' | 'dark';
  /** 文字に影を落とす。背景画像を敷いたときの可読性のため */
  textShadow: boolean;
  /** 前景の下に敷く覆いの濃さ。0 〜 1 */
  scrim: number;
}

export const DEFAULT_THEME: SetlistTheme = {
  textColor: 'light',
  textShadow: true,
  scrim: 0.45,
};

export interface RenderOptions {
  theme?: SetlistTheme;
  /** 出力サイズに整形済みの背景。setlistBackground.ts が作る */
  background?: CanvasImageSource | null;
}

interface Ink {
  palette: Palette;
  shadow: boolean;
}

/* 文字にだけ影を掛ける。罫線にまで乗るとにじんで見えるので、塗りの前に必ず戻す */
function beginText(ctx: Ctx, ink: Ink): void {
  if (!ink.shadow) return;
  ctx.shadowColor = ink.palette.shadow;
  ctx.shadowBlur = 18;
  ctx.shadowOffsetY = 2;
}

function endText(ctx: Ctx): void {
  ctx.shadowColor = 'transparent';
  ctx.shadowBlur = 0;
  ctx.shadowOffsetY = 0;
}

/* globals.css の --font-mono の写し。画像の中の文字はすべてこれ 1 本で組む */
const MONO = "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Noto Sans Mono', monospace";

const font = (weight: number, px: number, stack: string) => `${weight} ${px}px ${stack}`;

/* 以下の寸法はこの幅での px。実際の幅との比(unit)を掛けて使う */
const BASE_WIDTH = 1080;

/** サイズごとの寸法。1 回のレイアウト・描画で使い回す */
interface Metrics {
  width: number;
  height: number;
  /** 基準幅に対する倍率 */
  unit: number;
  side: number;
  contentW: number;
  padTop: number;
  /** ヘッダーの強調は色ではなく左の白い棒で作る(globals.css の .field-invalid と同じ理屈) */
  headerBarW: number;
  headerIndent: number;
  footerBaseline: number;
  footerRuleY: number;
  tracksBottom: number;
}

function metricsOf(size: SetlistSize): Metrics {
  const unit = size.width / BASE_WIDTH;
  const side = 72 * unit;
  const footerBaseline = size.height - 88 * unit;
  const footerRuleY = footerBaseline - 44 * unit;

  return {
    width: size.width,
    height: size.height,
    unit,
    side,
    contentW: size.width - side * 2,
    padTop: 96 * unit,
    headerBarW: 6 * unit,
    headerIndent: 28 * unit,
    footerBaseline,
    footerRuleY,
    tracksBottom: footerRuleY - 36 * unit,
  };
}

/* 縮尺の探索範囲。曲数が少ないときは 1.0 より大きく組んで余白を埋める。
   下限はゆったり組むときだけ SCALE_MIN で、詰めて組むときはサイズごとの minScale まで落とす */
const SCALE_MAX = 1.5;
const SCALE_MIN = 0.62;
const SCALE_STEP = 0.02;

const CREDIT = 'Generated by https://melocil.de/cue-parser';
const CREDIT_SIZE = 16;
const CREDIT_TRACK = 1.4;

export interface SetlistRow {
  no: string;
  title: string;
  performer: string;
}

export interface SetlistModel {
  title: string;
  performer: string;
  date: string;
  rows: SetlistRow[];
}

export interface SetlistOptions {
  /** タイトル・アーティストのヘッダーを出すか */
  showHeader: boolean;
  size: SetlistSize;
}

type DensityMode = 'comfortable' | 'compact';

interface HeaderLayout {
  barTop: number;
  barBottom: number;
  kickerBaseline: number;
  titleFontSize: number;
  titleLines: string[];
  titleFirstBaseline: number;
  titleLineHeight: number;
  performerBaseline: number;
  metaBaseline: number;
  meta: string;
  ruleY: number;
  tracksTop: number;
}

interface PreparedRow {
  no: string;
  titleLines: string[];
  performer: string;
  height: number;
}

export interface SetlistLayout {
  scale: number;
  mode: DensityMode;
  header: HeaderLayout;
  pages: PreparedRow[][];
  options: SetlistOptions;
}

/* ---------------- モデル ---------------- */

// REM DATE "2023" は parser がそのまま remarks に積むので、ここで剥がす
const DATE_RE = /^(?:REM\s+)?DATE\s+([\s\S]+)$/i;

function unquote(value: string): string {
  const trimmed = value.trim();
  const matched = /^"([\s\S]*)"$/.exec(trimmed);
  return (matched ? matched[1] : trimmed).trim();
}

export function buildSetlistModel(cueSheet: CueSheet): SetlistModel {
  const remarks = cueSheet.global.remarks ?? [];
  let date = '';
  for (let i = 0; i < remarks.length; i++) {
    const matched = DATE_RE.exec(remarks[i]);
    if (matched) {
      date = unquote(matched[1]);
      break;
    }
  }

  return {
    // 未入力時のフォールバックは youtube-serializer と揃える
    title: (cueSheet.global.title ?? '').trim() || 'Untitled',
    performer: (cueSheet.global.performer ?? '').trim(),
    date,
    rows: cueSheet.tracks.map((track) => ({
      no: String(track.number).padStart(2, '0'),
      title: (track.title ?? '').trim() || 'Untitled',
      performer: (track.performer ?? '').trim(),
    })),
  };
}

/* ---------------- 文字の計測 ---------------- */

type Ctx = CanvasRenderingContext2D;

// 日本語には単語境界が無いのでコードポイント単位で折る
const units = (text: string): string[] => Array.from(text);

// 行頭に来てほしくない文字(最低限の禁則)
const NO_LINE_START = /^[、。，．・:;!?」』）｝】〉》ー…ぁぃぅぇぉっゃゅょゎヵヶァィゥェォッャュョ]/;

function ellipsize(ctx: Ctx, text: string, maxWidth: number): string {
  if (ctx.measureText(text).width <= maxWidth) return text;

  const chars = units(text);
  let lo = 0;
  let hi = chars.length;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (ctx.measureText(chars.slice(0, mid).join('') + '…').width <= maxWidth) {
      lo = mid;
    } else {
      hi = mid - 1;
    }
  }

  return lo === 0 ? '…' : chars.slice(0, lo).join('').replace(/\s+$/, '') + '…';
}

function wrapText(ctx: Ctx, text: string, maxWidth: number, maxLines: number): string[] {
  if (ctx.measureText(text).width <= maxWidth) return [text];

  const chars = units(text);
  const lines: string[] = [];
  let line = '';

  for (let i = 0; i < chars.length; i++) {
    const char = chars[i];
    const next = line + char;

    if (line !== '' && ctx.measureText(next).width > maxWidth) {
      let carry = '';
      // 英字は直前の空白まで戻すと自然に折れる
      const space = line.lastIndexOf(' ');
      if (space > 0 && line.length - space <= 14) {
        carry = line.slice(space + 1);
        line = line.slice(0, space);
      } else if (NO_LINE_START.test(char) && line.length > 1) {
        carry = line.slice(-1);
        line = line.slice(0, -1);
      }

      lines.push(line);
      line = carry + char;

      if (lines.length === maxLines - 1) {
        lines.push(ellipsize(ctx, line + chars.slice(i + 1).join(''), maxWidth));
        return lines;
      }
    } else {
      line = next;
    }
  }

  if (line !== '') lines.push(line);
  return lines;
}

/* ctx.letterSpacing はブラウザ差が大きく、効かない環境では黙って無視される。
   出力を揃えたいので、字間は 1 文字ずつ描いて自前で作る */
function drawTracked(ctx: Ctx, text: string, x: number, y: number, track: number): void {
  const chars = units(text);
  let cursor = x;
  for (let i = 0; i < chars.length; i++) {
    ctx.fillText(chars[i], cursor, y);
    cursor += ctx.measureText(chars[i]).width + track;
  }
}

function trackedWidth(ctx: Ctx, text: string, track: number): number {
  const chars = units(text);
  if (chars.length === 0) return 0;
  let width = 0;
  for (let i = 0; i < chars.length; i++) {
    width += ctx.measureText(chars[i]).width + track;
  }
  return width - track;
}

/* ---------------- レイアウト ---------------- */

function planHeader(
  ctx: Ctx,
  model: SetlistModel,
  options: SetlistOptions,
  m: Metrics
): HeaderLayout {
  const u = m.unit;
  const textW = m.contentW - m.headerIndent;

  const barTop = m.padTop;
  const kickerBaseline = m.padTop + 22 * u;
  let y = kickerBaseline;

  let titleFontSize = 64 * u;
  let titleLines: string[] = [];
  let titleFirstBaseline = 0;
  let titleLineHeight = 0;
  let performerBaseline = 0;

  if (options.showHeader) {
    // 2 行に収まる一番大きい級数を採る
    for (; titleFontSize >= 40 * u; titleFontSize -= 4 * u) {
      ctx.font = font(600, titleFontSize, MONO);
      titleLines = wrapText(ctx, model.title, textW, 2);
      if (titleLines.length === 1 || titleLines[titleLines.length - 1].indexOf('…') === -1) break;
    }

    titleLineHeight = Math.round(titleFontSize * 1.18);
    y += 24 * u + titleFontSize;
    titleFirstBaseline = y;
    y += (titleLines.length - 1) * titleLineHeight;

    if (model.performer !== '') {
      y += (20 + 30) * u;
      performerBaseline = y;
    }
  }

  const metaParts: string[] = [];
  if (options.showHeader && model.date !== '') metaParts.push(model.date.toUpperCase());
  metaParts.push(`${model.rows.length} TRACKS`);

  y += (16 + 22) * u;
  const metaBaseline = y;
  const ruleY = metaBaseline + 40 * u;

  return {
    barTop,
    barBottom: metaBaseline + 6 * u,
    kickerBaseline,
    titleFontSize,
    titleLines,
    titleFirstBaseline,
    titleLineHeight,
    performerBaseline,
    metaBaseline,
    meta: metaParts.join(' · '),
    ruleY,
    tracksTop: ruleY + 44 * u,
  };
}

interface RowMetrics {
  numFont: string;
  titleFont: string;
  performerFont: string;
  numRight: number;
  textX: number;
  textW: number;
  titleLineHeight: number;
  performerLineHeight: number;
  padTop: number;
  padBottom: number;
  titleSize: number;
  performerSize: number;
  compactGap: number;
  compactPerformerW: number;
}

function rowMetrics(scale: number, mode: DensityMode, m: Metrics): RowMetrics {
  // 縮尺とサイズの倍率は同じ向きに効くので、掛け合わせて 1 つの係数にする
  const s = scale * m.unit;
  const numColW = 78 * s;
  const textW = m.contentW - numColW;

  return {
    numFont: font(500, 30 * s, MONO),
    titleFont: font(600, 34 * s, MONO),
    performerFont: font(400, 24 * s, MONO),
    numRight: m.side + numColW - 24 * s,
    textX: m.side + numColW,
    textW,
    titleLineHeight: 44 * s,
    performerLineHeight: 32 * s,
    padTop: (mode === 'comfortable' ? 8 : 10) * s,
    padBottom: (mode === 'comfortable' ? 14 : 12) * s,
    titleSize: 34 * s,
    performerSize: 24 * s,
    compactGap: 24 * s,
    compactPerformerW: textW * 0.36,
  };
}

function prepareRows(
  ctx: Ctx,
  model: SetlistModel,
  mode: DensityMode,
  scale: number,
  metrics: Metrics
): PreparedRow[] {
  const m = rowMetrics(scale, mode, metrics);

  return model.rows.map((row) => {
    if (mode === 'compact') {
      // タイトルとアーティストを 1 行に収める。アーティストは右端に寄せる
      const hasPerformer = row.performer !== '';
      ctx.font = m.performerFont;
      const performer = hasPerformer ? ellipsize(ctx, row.performer, m.compactPerformerW) : '';
      // アーティスト名は実寸ぶんだけ取り、残りをタイトルに回す(短い名前でタイトルを削らない)
      const performerW = hasPerformer ? ctx.measureText(performer).width : 0;
      const titleW = hasPerformer ? m.textW - performerW - m.compactGap : m.textW;
      ctx.font = m.titleFont;

      return {
        no: row.no,
        titleLines: [ellipsize(ctx, row.title, titleW)],
        performer,
        height: m.padTop + m.titleLineHeight + m.padBottom,
      };
    }

    ctx.font = m.titleFont;
    const titleLines = wrapText(ctx, row.title, m.textW, 2);
    ctx.font = m.performerFont;
    const performer = row.performer !== '' ? ellipsize(ctx, row.performer, m.textW) : '';

    return {
      no: row.no,
      titleLines,
      performer,
      height:
        m.padTop +
        titleLines.length * m.titleLineHeight +
        (performer !== '' ? m.performerLineHeight : 0) +
        m.padBottom,
    };
  });
}

function totalHeight(rows: PreparedRow[]): number {
  let sum = 0;
  for (let i = 0; i < rows.length; i++) sum += rows[i].height;
  return sum;
}

function fill(rows: PreparedRow[], available: number, maxPerPage: number): PreparedRow[][] {
  const pages: PreparedRow[][] = [];
  let current: PreparedRow[] = [];
  let used = 0;

  for (let i = 0; i < rows.length; i++) {
    const full = current.length >= maxPerPage || used + rows[i].height > available;
    if (current.length > 0 && full) {
      pages.push(current);
      current = [];
      used = 0;
    }
    current.push(rows[i]);
    used += rows[i].height;
  }
  if (current.length > 0) pages.push(current);

  return pages.length > 0 ? pages : [[]];
}

/**
 * まず詰められるだけ詰めて必要な枚数を出し、そのうえで枚数を変えずに均等割りする。
 * (最後のページだけ数曲、という間の抜けた絵にならないようにする)
 */
function paginate(rows: PreparedRow[], available: number): PreparedRow[][] {
  const greedy = fill(rows, available, Infinity);
  if (greedy.length < 2) return greedy;

  const balanced = fill(rows, available, Math.ceil(rows.length / greedy.length));
  return balanced.length <= greedy.length ? balanced : greedy;
}

/**
 * 1 枚に収める → 収まらなければ縮める → それでも駄目なら詰めて組む → 最後にページを割る。
 *
 * 縮尺は 0.02 刻みで上から探す。タイトルの折り返しが 1 行/2 行で切り替わるため
 * 行高は縮尺に対して階段状になり、二分探索は当てにできない。
 */
export function planSetlistLayout(
  ctx: Ctx,
  model: SetlistModel,
  options: SetlistOptions
): SetlistLayout {
  const m = metricsOf(options.size);
  const header = planHeader(ctx, model, options, m);
  const available = m.tracksBottom - header.tracksTop;
  const modes: DensityMode[] = ['comfortable', 'compact'];
  // ゆったり組むほうは行が 2 段になるので、小さくしても読みにくくなるだけ。
  // 深く詰めるのは 1 行組みのときだけにする
  const floorOf = (mode: DensityMode) => (mode === 'compact' ? options.size.minScale : SCALE_MIN);

  for (let i = 0; i < modes.length; i++) {
    for (let scale = SCALE_MAX; scale >= floorOf(modes[i]) - 1e-9; scale -= SCALE_STEP) {
      const rows = prepareRows(ctx, model, modes[i], scale, m);
      if (totalHeight(rows) <= available) {
        return { scale, mode: modes[i], header, pages: [rows], options };
      }
    }
  }

  // 最小の組みでも 1 枚に入らない → ページを割る。
  // まず最小の組みで必要な枚数を出し、その枚数を保てる中で一番大きい縮尺を採る
  // (枚数は最小のまま、文字はできるだけ大きく)
  const floor = floorOf('compact');
  const floorRows = prepareRows(ctx, model, 'compact', floor, m);
  const minPages = paginate(floorRows, available).length;

  for (let scale = SCALE_MAX; scale >= floor - 1e-9; scale -= SCALE_STEP) {
    const rows = prepareRows(ctx, model, 'compact', scale, m);
    const pages = paginate(rows, available);
    if (pages.length <= minPages) {
      return { scale, mode: 'compact', header, pages, options };
    }
  }

  return {
    scale: floor,
    mode: 'compact',
    header,
    pages: paginate(floorRows, available),
    options,
  };
}

/** レイアウト計算専用の 2D コンテキスト(画面には出さない) */
export function createMeasureContext(): Ctx | null {
  if (typeof document === 'undefined') return null;
  return document.createElement('canvas').getContext('2d');
}

/* ---------------- 描画 ---------------- */

function fillRule(ctx: Ctx, m: Metrics, y: number, height: number, color: string): void {
  ctx.fillStyle = color;
  ctx.fillRect(m.side, Math.round(y), m.contentW, height);
}

function drawHeader(
  ctx: Ctx,
  model: SetlistModel,
  layout: SetlistLayout,
  ink: Ink,
  m: Metrics
): void {
  const { header, options } = layout;
  const { palette } = ink;
  const u = m.unit;
  const textX = m.side + m.headerIndent;
  const textW = m.contentW - m.headerIndent;

  ctx.fillStyle = palette.fg;
  ctx.fillRect(m.side, header.barTop, m.headerBarW, header.barBottom - header.barTop);

  beginText(ctx, ink);
  ctx.textAlign = 'left';
  ctx.fillStyle = palette.muted;
  ctx.font = font(500, 22 * u, MONO);
  drawTracked(ctx, 'SETLIST', textX, header.kickerBaseline, 3.5 * u);

  if (options.showHeader) {
    ctx.fillStyle = palette.fg;
    ctx.font = font(600, header.titleFontSize, MONO);
    for (let i = 0; i < header.titleLines.length; i++) {
      ctx.fillText(
        header.titleLines[i],
        textX,
        header.titleFirstBaseline + i * header.titleLineHeight
      );
    }

    if (model.performer !== '' && header.performerBaseline > 0) {
      ctx.font = font(400, 30 * u, MONO);
      ctx.fillText(ellipsize(ctx, model.performer, textW), textX, header.performerBaseline);
    }
  }

  ctx.fillStyle = palette.muted;
  ctx.font = font(400, 22 * u, MONO);
  drawTracked(ctx, header.meta, textX, header.metaBaseline, 3 * u);
  endText(ctx);

  fillRule(ctx, m, header.ruleY, 2, options.showHeader ? palette.ruleStrong : palette.rule);
}

function drawFooter(
  ctx: Ctx,
  pageIndex: number,
  pageCount: number,
  ink: Ink,
  m: Metrics
): void {
  const { palette } = ink;
  const u = m.unit;
  fillRule(ctx, m, m.footerRuleY, 1, palette.rule);

  beginText(ctx, ink);
  ctx.textAlign = 'left';
  ctx.fillStyle = palette.muted;
  ctx.font = font(400, CREDIT_SIZE * u, MONO);
  drawTracked(ctx, CREDIT, m.side, m.footerBaseline, CREDIT_TRACK * u);

  if (pageCount > 1) {
    const label = `${pageIndex + 1} / ${pageCount}`;
    ctx.fillStyle = palette.fg;
    ctx.font = font(500, 24 * u, MONO);
    drawTracked(
      ctx,
      label,
      m.side + m.contentW - trackedWidth(ctx, label, 2 * u),
      m.footerBaseline,
      2 * u
    );
  }
  endText(ctx);
}

function drawRows(
  ctx: Ctx,
  layout: SetlistLayout,
  rows: PreparedRow[],
  ink: Ink,
  metrics: Metrics
): void {
  const { palette } = ink;
  const m = rowMetrics(layout.scale, layout.mode, metrics);
  const available = metrics.tracksBottom - layout.header.tracksTop;
  const used = totalHeight(rows);

  // 余白の扱い。まず行間に配り(1 つあたり行高の 2.5 倍まで)、
  // 残りは上下で割って、曲数が少なくても縦の中央に寄るようにする
  const gaps = Math.max(rows.length - 1, 0);
  const leftover = Math.max(0, available - used);
  const extra = gaps > 0 ? Math.min(leftover / gaps, m.titleLineHeight * 2.5) : 0;

  let y = layout.header.tracksTop + (leftover - extra * gaps) / 2;

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const firstBaseline = y + m.padTop + m.titleSize * 0.8;

    beginText(ctx, ink);
    ctx.textAlign = 'right';
    ctx.fillStyle = palette.muted;
    ctx.font = m.numFont;
    ctx.fillText(row.no, m.numRight, firstBaseline);

    ctx.textAlign = 'left';
    ctx.fillStyle = palette.fg;
    ctx.font = m.titleFont;
    for (let line = 0; line < row.titleLines.length; line++) {
      ctx.fillText(row.titleLines[line], m.textX, firstBaseline + line * m.titleLineHeight);
    }

    if (row.performer !== '') {
      ctx.fillStyle = palette.muted;
      ctx.font = m.performerFont;
      if (layout.mode === 'compact') {
        ctx.textAlign = 'right';
        ctx.fillText(row.performer, metrics.side + metrics.contentW, firstBaseline);
        ctx.textAlign = 'left';
      } else {
        ctx.fillText(
          row.performer,
          m.textX,
          y + m.padTop + row.titleLines.length * m.titleLineHeight + m.performerSize * 0.85
        );
      }
    }

    endText(ctx);
    y += row.height;

    if (i < rows.length - 1) {
      // 罫線は行間の真ん中に置く
      ctx.fillStyle = palette.hairline;
      ctx.fillRect(m.textX, Math.round(y + extra / 2) - 1, metrics.side + metrics.contentW - m.textX, 1);
      y += extra;
    }
  }
}

/**
 * 前景の下に敷く覆い。globals.css が「シェーダの輝度上限 + .bg-veil」の二段で暗さを作っているのと
 * 同じ考えで、画像側の明るさとは別にここでもう一枚敷く。
 * 上下の端は文字が小さいので、濃さの指定とは無関係に常に沈めておく。
 */
function drawScrim(ctx: Ctx, palette: Palette, strength: number, m: Metrics): void {
  if (strength > 0) {
    ctx.fillStyle = `rgba(${palette.scrim}, ${strength})`;
    ctx.fillRect(0, 0, m.width, m.height);
  }

  const veil = ctx.createLinearGradient(0, 0, 0, m.height);
  veil.addColorStop(0, `rgba(${palette.scrim}, 0.55)`);
  veil.addColorStop(0.22, `rgba(${palette.scrim}, 0)`);
  veil.addColorStop(0.8, `rgba(${palette.scrim}, 0)`);
  veil.addColorStop(1, `rgba(${palette.scrim}, 0.55)`);
  ctx.fillStyle = veil;
  ctx.fillRect(0, 0, m.width, m.height);
}

export function renderSetlistPage(
  canvas: HTMLCanvasElement,
  model: SetlistModel,
  layout: SetlistLayout,
  pageIndex: number,
  render?: RenderOptions
): void {
  // バッキングストアは選んだサイズちょうど。devicePixelRatio は掛けない
  // (どの端末でも同じ PNG が出ることが要件)
  const m = metricsOf(layout.options.size);
  if (canvas.width !== m.width) canvas.width = m.width;
  if (canvas.height !== m.height) canvas.height = m.height;

  const ctx = canvas.getContext('2d', { alpha: false });
  if (!ctx) return;

  const theme = render?.theme ?? DEFAULT_THEME;
  const background = render?.background ?? null;
  const palette = theme.textColor === 'dark' ? DARK_PALETTE : LIGHT_PALETTE;
  // 影が要るのは背景画像を敷いたときだけ。黒地のときは元の平らな絵のままにする
  const ink: Ink = { palette, shadow: theme.textShadow && background !== null };

  ctx.fillStyle = COLOR_BG;
  ctx.fillRect(0, 0, m.width, m.height);

  if (background) {
    // 背景は同じサイズに整形済みなので等倍で貼る
    ctx.drawImage(background, 0, 0, m.width, m.height);
    drawScrim(ctx, palette, theme.scrim, m);
  }

  ctx.textBaseline = 'alphabetic';
  endText(ctx);

  drawHeader(ctx, model, layout, ink, m);

  const rows = layout.pages[pageIndex] ?? [];
  if (rows.length === 0) {
    beginText(ctx, ink);
    ctx.textAlign = 'left';
    ctx.fillStyle = palette.muted;
    ctx.font = font(400, 28 * m.unit, MONO);
    const label = 'NO TRACKS';
    drawTracked(
      ctx,
      label,
      (m.width - trackedWidth(ctx, label, 4 * m.unit)) / 2,
      (layout.header.tracksTop + m.tracksBottom) / 2,
      4 * m.unit
    );
    endText(ctx);
  } else {
    drawRows(ctx, layout, rows, ink, m);
  }

  drawFooter(ctx, pageIndex, layout.pages.length, ink, m);
}

/* ---------------- ファイル名 ---------------- */

export function sanitizeFileName(raw: string): string {
  const cleaned = raw
    .replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^\.+/, '')
    .slice(0, 80)
    .trim();
  return cleaned || 'setlist';
}

export function setlistFileName(model: SetlistModel, pageIndex: number, pageCount: number): string {
  const suffix = pageCount > 1 ? `_${pageIndex + 1}` : '';
  return `${sanitizeFileName(model.title)}_setlist${suffix}.png`;
}
